# Generated by Django 3.2.13 on 2022-06-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='images/books/<django.db.models.fields.IntegerField>/<django.db.models.fields.CharField>'),
        ),
    ]
