# Generated by Django 3.2.13 on 2022-06-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20220616_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookgenre',
            options={'ordering': ['name'], 'verbose_name': 'жанр книги', 'verbose_name_plural': 'жанры книг'},
        ),
        migrations.AddField(
            model_name='book',
            name='age_restrictions',
            field=models.CharField(default='18+', max_length=50, verbose_name='Возрастные ограничения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='images/books/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='bookgenre',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Наименование'),
        ),
    ]
