# Generated by Django 3.2.13 on 2022-06-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20220616_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_link',
            field=models.CharField(max_length=200, null=True, verbose_name='Ссылка на livelib'),
        ),
    ]
