# Generated by Django 3.2.13 on 2022-06-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_book_book_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на livelib'),
        ),
    ]
